curl localhost:8080/weather/paris     ; echo
curl localhost:8080/weather/london    ; echo
curl localhost:8080/weather/berlin    ; echo
curl localhost:8080/weather/madrid    ; echo
curl localhost:8080/weather/tokyo     ; echo
curl localhost:8080/weather/lima      ; echo
curl localhost:8080/weather/lisboa    ; echo
curl localhost:8080/weather/ibiza     ; echo
curl localhost:8080/weather/piruleta  ; echo
curl localhost:8080/weather/oslo      ; echo
curl localhost:8080/weather/stockholm ; echo